#!/bin/bash

# Setup script for pushing PAI planning files to GitHub
# Usage: ./setup_github.sh [repo-name]

echo "🚀 PAI Planning Files - GitHub Setup"
echo "===================================="
echo ""

# Default repository name
REPO_NAME=${1:-"pai-planning"}

echo "📝 Repository Setup Instructions:"
echo ""
echo "1. First, create a new repository on GitHub:"
echo "   - Go to: https://github.com/kp2031?tab=repositories"
echo "   - Click 'New' button"
echo "   - Repository name: $REPO_NAME"
echo "   - Description: 'Personal AI Infrastructure - Planning & Architecture'"
echo "   - Keep it Public or Private as preferred"
echo "   - DO NOT initialize with README (we have our own)"
echo "   - Click 'Create repository'"
echo ""
echo "2. After creating the repository, run ONE of these commands:"
echo ""
echo "   Option A - If you created a repo named '$REPO_NAME':"
echo "   ----------------------------------------"
echo "   git remote add origin https://github.com/kp2031/$REPO_NAME.git"
echo "   git push -u origin main"
echo ""
echo "   Option B - If you used a different name:"
echo "   ----------------------------------------"
echo "   git remote add origin https://github.com/kp2031/YOUR_REPO_NAME.git"
echo "   git push -u origin main"
echo ""
echo "3. Verify success by visiting:"
echo "   https://github.com/kp2031/$REPO_NAME"
echo ""
echo "📌 Current Git Status:"
echo "----------------------"
git status --short
echo ""
echo "📊 Repository Statistics:"
echo "------------------------"
echo "Files ready to push: $(git ls-files | wc -l)"
echo "Total size: $(du -sh . | cut -f1)"
echo "Latest commit: $(git log --oneline -1)"
echo ""
echo "✅ Your local repository is ready to push!"
echo ""
echo "🔐 Authentication Notes:"
echo "-----------------------"
echo "If prompted for authentication, you'll need either:"
echo "- GitHub Personal Access Token (recommended)"
echo "- Your GitHub password (if 2FA is not enabled)"
echo ""
echo "To create a Personal Access Token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Give it a name like 'PAI Planning Repo'"
echo "4. Select 'repo' scope"
echo "5. Generate and copy the token"
echo "6. Use the token as your password when pushing"